# Generated by Django 3.0.4 on 2020-03-23 05:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0002_auto_20200319_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Name should only consist of characters', regex='^[a-zA-Z]+$')])),
                ('postalcode', models.IntegerField(unique=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcare_app.State')),
            ],
        ),
    ]
