# Generated by Django 3.0.4 on 2020-03-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0003_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'name')},
        ),
    ]
