# Generated by Django 3.0.4 on 2020-03-23 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0004_auto_20200323_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name should only consist of characters', regex='^[a-zA-Z]+$')]),
        ),
    ]
