# Generated by Django 3.0.4 on 2020-03-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0005_auto_20200323_1332'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
    ]
