# Generated by Django 3.0.4 on 2020-03-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0006_auto_20200323_1432'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'name')},
        ),
    ]
