# Generated by Django 3.0.4 on 2020-03-24 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0009_auto_20200324_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name should consist of characters', regex='(?i)^\\d*[a-zA-Z][#.0-9a-zA-Z\\s,-]+$')]),
        ),
    ]
