# Generated by Django 3.0.4 on 2020-03-24 06:54

import django.core.validators
from django.db import migrations
import healthcare_app.models.facility


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0011_auto_20200324_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='name',
            field=healthcare_app.models.facility.NameField(default=2, max_length=100, validators=[django.core.validators.RegexValidator(message='Name should consist of characters', regex='^\\d*[a-zA-Z][#.0-9a-zA-Z\\s,-]+$')]),
            preserve_default=False,
        ),
    ]
