# Generated by Django 3.0.4 on 2020-03-24 07:05

import django.core.validators
from django.db import migrations
import healthcare_app.models.facility


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0012_facility_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=healthcare_app.models.facility.NameField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name should consist of character', regex='^\\d*[a-zA-Z][#.0-9a-zA-Z\\s,-]+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('city', 'name')},
        ),
    ]
